#!/usr/bin/python

class MyGlobals(object):
    ping = 0
    #tcp = 0
    source = ' '
    dest = ' '
    emwa=0
    web_load=[0]
    tcp_flows=0
    emwa_pre=0
    x=0
    i=0
    x_pre=0
    sd_pre=0
    emwa_r_pre=0
    sd_r_pre=0
    thresh_1=0
    thresh_2=0
    flow_threshold=5
    p_ratio=0
    flow_id=1
    tcp_id=0
    ack_id=0
    acks=0
    t_packet=0
    t_flows=0
    s_port=0
    d_port=0
    web_mean=0
    web_sd=0
    old_t_flow=0
    new_t_flow=0
    old_t_packet=0
    new_t_packet=0
    end_timer = 0
    #table=''
    #f_no=1
    timer=0
    #t_out=0
    my_tuple=()
    t_stat=0
    p_ratio=0
    tcp_syn_flows=0
    p_stat=0
    stat_id=0
    thresh_2=0
    back_off=1 #Starting Value is 1 because "1" is multiplicative inverse
